/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface IdliGrid {
    'columnConfig': any[] | string;
    'data': any[] | string;
  }
}

declare global {


  interface HTMLIdliGridElement extends Components.IdliGrid, HTMLStencilElement {}
  var HTMLIdliGridElement: {
    prototype: HTMLIdliGridElement;
    new (): HTMLIdliGridElement;
  };
  interface HTMLElementTagNameMap {
    'idli-grid': HTMLIdliGridElement;
  }
}

declare namespace LocalJSX {
  interface IdliGrid {
    'columnConfig'?: any[] | string;
    'data'?: any[] | string;
  }

  interface IntrinsicElements {
    'idli-grid': IdliGrid;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'idli-grid': LocalJSX.IdliGrid & JSXBase.HTMLAttributes<HTMLIdliGridElement>;
    }
  }
}


